# This file controls the AWS CodeBuild

version: 0.2
phases: 
  pre_build:
    commands: 
    - echo "Entering the preBuild phase"
  build:
    commands: 
    - echo "Entering the build phase"
    
  post_build:
    commands:
    - echo "Entering the post build phase"
    - echo "compiling the code"
    - mvn compile
    - echo "compilation is done"
    - echo "making a jar"
    - mvn package
    - echo "jar creation is done"
artifacts: 
  files:
    - 'target/spring-boot-restAPI-0.0.1-SNAPSHOT.jar'
    